### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by firecat53** [qdm12/deunhealth#5]
**Host OS** (approximate answer is fine too): Fedora 34

**Is this urgent?**: No

**What is the version of the program** (See the line at the top of your logs)

N/A - failure to build current git commit 196b83433 

**What's the problem** 🤔

Docker build fails twice:

`docker build -t unhealth .`

1. `RUN apk --update add git g++` I think should be `apk --no-cache`
2. Not sure what this failure is from:

		go: found github.com/morikuni/aec in github.com/morikuni/aec v1.0.0
		go: found golang.org/x/time/rate in golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac
		diff --git a/go.mod b/go.mod
		index c5394ae..bf6c9bd 100644
		--- a/go.mod
		+++ b/go.mod
		@@ -32,6 +32,6 @@ require (
				golang.org/x/sys v0.0.0-20210616094352-59db8d763f22 // indirect
				golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac // indirect
				google.golang.org/genproto v0.0.0-20201110150050-8816d57aaa9a // indirect
		-       google.golang.org/grpc v1.40.0 // indirect
		+       google.golang.org/grpc v1.41.0 // indirect
				google.golang.org/protobuf v1.26.0 // indirect
		 )
		The command '/bin/sh -c git init &&     git config user.email ci@localhost &&     git config user.name ci &&     git add -A && git commit -m ci &&     sed -i '/\/\/ indirect/d' go.mod &&     go mod tidy &&     git diff --exit-code -- go.mod' returned a non-zero code: 1

**Share your logs...**

N/A

**Comment by qdm12** [comment]
You should set `DOCKER_BUILDKIT=1`, because I believe you build every stages (old Docker build way), even test ones.

If you run:

```sh
DOCKER_BUILDKIT=1 docker build -t qmcgaw/deunhealth https://github.com/qdm12/deunhealth.git
```

It will just build the binary and the final image (without those additional test + lint + tidy stages).

Anyway, a101dd3c89e11045159115c18df44b2bb7f060e9 and e9a12e1357c960fc5968ee4067821d32e61b3b5f fix the `tidy` stage issue you had. In the end, I also removed it in 863cf470d90a4e7cc8aa650a2b2602beaa0260b1 since it does not make sense to run anymore (TLDR: with Go 1.17, things changed).

**Comment by qdm12** [comment]
I also just made a release v0.2.0. If you want you can build it with:

```sh
DOCKER_BUILDKIT=1 docker build -t qmcgaw/deunhealth https://github.com/qdm12/deunhealth.git#v0.2.0
```

(unless you want to fiddle with the code of course)

**Comment by firecat53** [comment]
Thanks, works great! FWIW, found this project from the Console newsletter today
and thought it seemed like a somewhat cleaner implementation than the autohealth
container.

**Comment by qdm12** [comment]
I thought you did 😅!

It has zero coverage on social media or anywhere outside that console interview (running low on time and don't want yet another popular repo... ironic isn't it!)

But yeah I agree with you, that autoheal container hurts my programmer soul seeing it doing periodic checks in a shell script 😉
